### ISSUE TITLE
I can not hide the remove Filter button

### ISSUE THREAD

**Issue by Jucesr** [MarilesBeard5/semantic-table#1]
I am not able to remove the **Limpiar filtros** button. It's really annoying. Please do something or I will stop using this component

**Comment by MarilesBeard5** [comment]
> I am not able to remove the **Limpiar filtros** button. It's really annoying. Please do something or I will stop using this component

Create a fork and do it yourself

**Comment by Jucesr** [comment]
> 

This is how you treat your followers?
